version: '3.8'

services:
  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - node-service-1
      - node-service-2
      - node-service-3

  node-service-1:
    build: ./docker/api
    environment:
      - DB_HOST=db
      - DB_USERNAME=app_user
      - DB_PASSWORD=An0th3rS3cure!
      - DB_DATABASE=app_db

  node-service-2:
    build: ./docker/api
    environment:
      - DB_HOST=db
      - DB_USERNAME=app_user
      - DB_PASSWORD=An0th3rS3cure!
      - DB_DATABASE=app_db

  node-service-3:
    build: ./docker/api
    environment:
      - DB_HOST=db
      - DB_USERNAME=app_user
      - DB_PASSWORD=An0th3rS3cure!
      - DB_DATABASE=app_db

  db:
    build: ./docker/db
    environment:
      - MYSQL_ROOT_PASSWORD=S3cur3P@ss!
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=An0th3rS3cure!
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: